### ISSUE TITLE
Can I pass command line arguments to my tests?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [cucumber/godog#198]
I want to use godog to run appium tests. I want to run these tests under different contexts (android, iOS, tablet, phone).

There are slight variations in the initialization and step definitions depending on for which device and OS I am running the tests on.

Can I somehow pass arguments to my tests, so that the same test code can run for all devices?

**Comment by l3pp4rd** [comment]
Hi, yes you can create any flags and extend godog flags if you want to customize it, best through `go test` look in the [guide](https://github.com/DATA-DOG/godog#running-godog-with-go-test) This then can be run with standard `go test` command. If you still want to use `godog` command, then you may need to compile one with your additional flags configured, based on the current [godog command line tool](https://github.com/DATA-DOG/godog/blob/master/cmd/godog/main.go) only 100 lines of code, you can adjust the flags based on your needs. (but safer and suggested way, just to integrate with go test together)

**Comment by jaysonesmith** [comment]
@RudolfVonKrugstein Were you able to get things going as you needed? Another idea that might be viable is to set an env variable and check that in your functions.

If you're all set here, could you close this issue out please otherwise comment and let us know what's up. If neither happens, I'll close this issue in a week.

Thanks!
