### ISSUE TITLE
Is there any way to retry a failed scenario?

### ISSUE THREAD

**Issue by rubencougil** [cucumber/godog#199]
Would be great to have a mechanism to retry n times if a tests had failed. Is there anything like this in godogs?

**Comment by l3pp4rd** [comment]
Yes, you can run a single scenario as **godog features/scenario.fature:30**  where colon 30 is the line number of scenario. Progress or pretty formatter prints the line number of scenario so you can just copy it and run

**Comment by rubencougil** [comment]
i mean, not just executing a simple scenario, but retrying it automatically if it fails because is flacky. Would be something like https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html

**Comment by l3pp4rd** [comment]
No, there are no options to auto retry, you may do the auto retry on the individual step since you implement it, but in general, having flacky tests even with auto retries is not the recommended way to develop the test suites. If test can fail once it may fail more times in a row causing the same problems. Better resolve it in propper ways

**Comment by l3pp4rd** [comment]
In case if you really want to go this path, fork and add the option

**Comment by lonnblad** [comment]
Hi, based on the answer from l3pp4rd, I will close this issue with wontfix.

BR
Fredrik

**Comment by harikamankala** [comment]
I am looking for this. Can we expect this feature soon in godog?
