### ISSUE TITLE
Update Gherkin-go to last version

### ISSUE THREAD

**Issue by inluxc** [cucumber/godog#202]
We need to update the gherkin-go library to the latest version v.9.0.0, so we can fix problems like  #124, to add attachments to the step error messages.

**Comment by l3pp4rd** [comment]
Hi, integrating later gherkin version, would require protobuf dependency, in my opinion test related libraries should not have chains of dependencies.

Though, since I do not have time now to properly maintain this library, it may be considerable to move it to cucumber organization if there would be maintainers. they probably would instantly migrate it to recent gherkin version.

**Comment by l3pp4rd** [comment]
will speak to the cucumber organization about migration of the repository and handing over the main maintenance.

**Comment by lonnblad** [comment]
@l3pp4rd hey, did you get a chance to talk to them?
if you would want to, I can help you to maintain the repo otherwise

**Comment by l3pp4rd** [comment]
yes I've sent the email a month ago, but got no response yet, so probably it got lost or forgotten, will resend it again, and probably try other channels

**Comment by l3pp4rd** [comment]
got the response fast today, will be moving it to cucumber organization, it should receive more proper maintenance!

**Comment by lonnblad** [comment]
I have issues with the setup of the gherkin-go repo and the go guidelines.
```
require github.com/cucumber/gherkin-go: version "v9.2.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v9
```

From the go cmd documentation
```
To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2, and packages in that module would use that path as their import path prefix, as in example.com/m/v2/sub/pkg.
```

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by lonnblad** [comment]
@l3pp4rd could you address this with the cucumber guys? it seems they don't have issues enabled on the gherkin-go repo.

**Comment by lonnblad** [comment]
I was planning to take a stab at this and see if I can sort it out

**Comment by l3pp4rd** [comment]
may not be that simple, since there were changes in gherkin `Rule` added, the pretty formatter will change. though, would be best to find ways how to do it incrementally. maybe just supporting new lib and current gherkin features present. then next step after library is migrated, implement the new features, such as Rule keyword. Also later, based on other cucumber implementations, it seems to be better to compile gherkin Scenario outline to separate scenario list given all the examples in table. though, you could have a look at cucumber-js. but first just library migration, do not step into large refactorings because it will slow you down, do it incrementally.

**Comment by lonnblad** [comment]
yep, agree
