### ISSUE TITLE
test-level context

### ISSUE THREAD

**Issue by Lewiscowles1986** [cucumber/godog#357]
**Is your feature request related to a problem? Please describe.**

I would like to be able to test an application e2e, and maintain state between steps blackbox

**Describe the solution you'd like**

Each test to have their own ability to define a context (probably it's shape too using custom struct) which allows steps to communicate.

**Describe alternatives you've considered**

I Haven't... I'm having a hard time thinking of how else I would communicate blackbox. I'm not a big fan of whitebox testing.

**Additional context**

I'm trying to write an e2e test using godogs. Usually when I've used Gherkin, I've worked in a language with classes, which I can stuff context into. I Guess I could do that here too, but it's feature specific so I don't think I'll be able to run them concurrently. (Maybe I need to understand more about godogs)

**Comment by lonnblad** [comment]
Hi @Lewiscowles1986

I would suggest to have a look at the [api-example](https://github.com/cucumber/godog/blob/master/_examples/api/api_test.go).

You should be able to share state between steps using a struct like this:
```go
type apiFeature struct {
	resp *httptest.ResponseRecorder
}
```

Since the scenarios run concurrent, the apiFeature variable will only live within the context of one scenario.
```go
func InitializeScenario(ctx *godog.ScenarioContext) {
	api := &apiFeature{}

	ctx.BeforeScenario(api.resetResponse)

	// ...
}
```

If you want too, you can also head into the [#help-godog](https://cucumberbdd.slack.com/archives/CTNL1JCVA) channel on our [Cucumber Slack Community](https://cucumberbdd.slack.com/).
Join the community [here](https://cucumberbdd-slack-invite.herokuapp.com/).

**Comment by Lewiscowles1986** [comment]
I had looked but clearly the syntax was new too 😊 apologies, and thank you!

**Comment by lonnblad** [comment]
no need, happy to help!
