### ISSUE TITLE
How come we don't run `go test ./...`?

### ISSUE THREAD

**Issue by mattwynne** [cucumber/godog#458]
## What's the problem you've observed? 🤔

In `make test` and our CI workflows, we just run `go test` which as I understand it only runs the tests in the root. There are lots of other tests in sub-folders, which as far as I can tell aren't being run by our CI or `make test` command.

## Do you have a proposal for making it better? 🦄

I'm not a Go expert, but would it not be better to run `go test ./...` instead?

**Comment by vearutop** [comment]
Interesting indeed, we have this for ~7 years since https://github.com/cucumber/godog/commit/3ec64f42c9b4c514e2fd76b7a2e8049a3392b27b. 
Not sure what was original reasoning, maybe because by that time we only had `examples` as additional package.

I think we should run `go test -race ./...` and fortunately it still passes. :)

**Comment by mattwynne** [comment]
A reminder to always try and put a "why" in your git commit messages :)

It turns out I was wrong about CI, the [GitHub Action `test.yml`](https://github.com/cucumber/godog/blob/main/.github/workflows/test.yml#L42) does run in `./...` so this is probably why it's not become much of an issue.
