### ISSUE TITLE
Implement unambiguous keywords

### ISSUE THREAD

**Issue by mattwynne** [cucumber/godog#479]
As described in https://github.com/cucumber/common/issues/768

**Comment by otrava7** [comment]
Godog currently doesn't have separate functions for different step types, we just use the `Step` function which takes a regex and a function. What are peoples thoughts of introducing functions for the different keywords as a first step? Having those functions would make it possible to record the keyword type so that we may assert it when matching in order to resolve the issue detailed above.

**Comment by otrava7** [comment]
I've gotten started on creating keyword functions and capturing the keywords. Will submit a PR once the logic for enabling unambiguous keywords is implemented:
https://github.com/cucumber/godog/compare/main...otrava7:godog:implement-unambiguous-keywords
