### ISSUE TITLE
hooks return error

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/godog#88]
Currently the return values of hooks is not used. I'd like to be able to return an error in BeforeScenario/AfterScenario (and the other steps) and have it printed as as error instead of having to panic as my current workaround

**Comment by Dogild** [comment]
I have fixed this issue by using this patch https://github.com/DATA-DOG/godog/pull/62 -> not sure if it's up to date though

**Comment by l3pp4rd** [comment]
@charlierudolph I think this is valid point to consider adding a return value to all hooks, because that would be an idiomatic way to error in such cases like before scenario. @Dogild your version is not exactly related to what was asked. If we allow for hooks to return an error and fail the scenario, then you may stop on the first failure and quit a suite. That is a much better way, compared to adding another option to manage that.

**Comment by l3pp4rd** [comment]
that should be implemented at some point, it is just that it will break the backward compatibility. maybe I'll think a little more what could be done with that together if there are other parts needing a BC break and similar refactoring.

**Comment by Dogild** [comment]
@l3pp4rd totally agree, my version was just a way to not break the existing API. As soon we will be able to return error in a hook, I'll remove my path in my private fork....

**Comment by l3pp4rd** [comment]
yes, I'm just thinking about more BC changes which may be necessary to make this all at once. or maybe if we have some time we can make a command `godog fix` like `go fix` to walk source AST and fix all backaward incompatible issues.

**Comment by ess** [comment]
Just to throw a "me too" into the hat, this would be so handy that I'm pretty sure it's worth the BC, particularly since you've specifically stated that pre-1.0 API changes are to be expected.

**Comment by l3pp4rd** [comment]
yes, will need to jump to this when I have time ;)

**Comment by tcagan** [comment]
Migrating from Java - we're also missing this feature (+1 here as well)

**Comment by zhammer** [comment]
Bumping on this old issue. It would be great to be able to return errors from scenario / test suite fixtures.

Not sure what was decided on breaking changes, but happy to help with a PR.

**Comment by lonnblad** [comment]
Hi @zhammer 

Not super up to date with this one, but if we do breaking changes to the hooks, I would like us to also look at a design that incorporates attachments, since that is a feature supported by other cucumber implementations and have been asked for here as well.

I'm not asking for an implementation of attachments, but I think we need a design that could be extended for it without more breaking changes.

Regarding breaking changes in general, when possible, we would like to be able to mark the old as deprecated for one release, before we remove it. If that is not possible, we need to think about how we can make the transition easy for someone updating to this version.

**Comment by lonnblad** [comment]
Hi, if you have time, please check out the suggestion in #360 and comment there if you have would like to see changes.
